package deadliner;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import deadliner.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2017.03.30 13:51:28 // Generated by ComTest
 *
 */
public class PrioriteetitTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa32 
   * @throws Poikkeus when error
   */
  @Test
  public void testLisaa32() throws Poikkeus {    // Prioriteetit: 32
    Prioriteetit prioriteetit = new Prioriteetit(); 
    Prioriteetti yksi = new Prioriteetti(), kaksi = new Prioriteetti(); 
    assertEquals("From: Prioriteetit line: 36", 0, prioriteetit.getLkm()); 
    prioriteetit.lisaa(yksi); assertEquals("From: Prioriteetit line: 37", 1, prioriteetit.getLkm()); 
    prioriteetit.lisaa(kaksi); assertEquals("From: Prioriteetit line: 38", 2, prioriteetit.getLkm()); 
    prioriteetit.lisaa(yksi); assertEquals("From: Prioriteetit line: 39", 3, prioriteetit.getLkm()); 
    assertEquals("From: Prioriteetit line: 40", yksi, prioriteetit.viittaa(0)); 
    assertEquals("From: Prioriteetit line: 41", kaksi, prioriteetit.viittaa(1)); 
    assertEquals("From: Prioriteetit line: 42", yksi, prioriteetit.viittaa(2)); 
    assertEquals("From: Prioriteetit line: 43", false, prioriteetit.viittaa(1) == yksi); 
    assertEquals("From: Prioriteetit line: 44", true, prioriteetit.viittaa(1) == kaksi); 
    try {
    assertEquals("From: Prioriteetit line: 45", yksi, prioriteetit.viittaa(3)); 
    fail("Prioriteetit: 45 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    prioriteetit.lisaa(yksi); assertEquals("From: Prioriteetit line: 46", 4, prioriteetit.getLkm()); 
    prioriteetit.lisaa(yksi); assertEquals("From: Prioriteetit line: 47", 5, prioriteetit.getLkm()); 
    try {
    prioriteetit.lisaa(yksi); 
    fail("Prioriteetit: 48 Did not throw Poikkeus");
    } catch(Poikkeus _e_){ _e_.getMessage(); }
  } // Generated by ComTest END
}