package deadliner;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import deadliner.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2017.03.30 14:01:56 // Generated by ComTest
 *
 */
public class TehtavaTest {



  // Generated by ComTest BEGIN
  /** testGetNimi37 */
  @Test
  public void testGetNimi37() {    // Tehtava: 37
    Tehtava yksi = new Tehtava(); 
    yksi.lisaaTestiarvot(1); 
    { String _l_=yksi.getNimi(),_r_="HT Vaihe.*"; if ( !_l_.matches(_r_) ) fail("From: Tehtava line: 40" + " does not match: ["+ _l_ + "] != [" + _r_ + "]");}; 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testLuoId50 */
  @Test
  public void testLuoId50() {    // Tehtava: 50
    Tehtava yksi = new Tehtava(); 
    assertEquals("From: Tehtava line: 52", 0, yksi.getId()); 
    yksi.luoId(); 
    Tehtava kaksi = new Tehtava(); 
    kaksi.luoId(); 
    int n1 = yksi.getId(); 
    int n2 = kaksi.getId(); 
    assertEquals("From: Tehtava line: 58", n2 - 1, n1); 
  } // Generated by ComTest END
}