package deadliner;
// Generated by ComTest BEGIN
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
import deadliner.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2017.03.30 04:09:11 // Generated by ComTest
 *
 */
public class TehtavatTest {



  // Generated by ComTest BEGIN
  /** testIterator56 */
  @Test
  public void testIterator56() {    // Tehtavat: 56
    Tehtavat teet = new Tehtavat(); 
    Tehtava yksi = new Tehtava(1); teet.lisaa(yksi); 
    Tehtava kaksi = new Tehtava(3); teet.lisaa(kaksi); 
    Tehtava kolme = new Tehtava(2); teet.lisaa(kolme); 
    Tehtava nelja = new Tehtava(1); teet.lisaa(nelja); 
    Tehtava viisi = new Tehtava(3); teet.lisaa(viisi); 
    Iterator<Tehtava> i2 = teet.iterator(); 
    assertEquals("From: Tehtavat line: 67", yksi, i2.next()); 
    assertEquals("From: Tehtavat line: 68", kaksi, i2.next()); 
    assertEquals("From: Tehtavat line: 69", kolme, i2.next()); 
    assertEquals("From: Tehtavat line: 70", nelja, i2.next()); 
    assertEquals("From: Tehtavat line: 71", viisi, i2.next()); 
    try {
    assertEquals("From: Tehtavat line: 72", nelja, i2.next()); 
    fail("Tehtavat: 72 Did not throw NoSuchElementException");
    } catch(NoSuchElementException _e_){ _e_.getMessage(); }
    int n = 0; 
    int tnrot[] = { 1,3,2,1,3} ; 
    for ( Tehtava teh : teet ) {
    assertEquals("From: Tehtavat line: 78", tnrot[n], teh.getId()); n++; 
    }
    assertEquals("From: Tehtavat line: 81", 5, n); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testHaeTehtavat93 */
  @Test
  public void testHaeTehtavat93() {    // Tehtavat: 93
    Tehtavat teet = new Tehtavat(); 
    Tehtava yksi = new Tehtava(1); teet.lisaa(yksi); 
    Tehtava kaksi = new Tehtava(3); teet.lisaa(kaksi); 
    Tehtava kolme = new Tehtava(2); teet.lisaa(kolme); 
    Tehtava nelja = new Tehtava(1); teet.lisaa(nelja); 
    Tehtava viisi = new Tehtava(3); teet.lisaa(viisi); 
    List<Tehtava> loydetyt; 
    loydetyt = teet.haeTehtavat(0); 
    assertEquals("From: Tehtavat line: 104", 0, loydetyt.size()); 
    loydetyt = teet.haeTehtavat(3); 
    assertEquals("From: Tehtavat line: 106", 2, loydetyt.size()); 
    assertEquals("From: Tehtavat line: 107", true, loydetyt.get(0) == kaksi); 
    assertEquals("From: Tehtavat line: 108", true, loydetyt.get(1) == viisi); 
  } // Generated by ComTest END
}